### ISSUE TITLE
One cycle instead of two

### ISSUE THREAD

**Issue by IanaKhitsko** [akorunska/euro-diffusion#10]
https://github.com/akorunska/euro-diffusion/blob/0988f5fe91d81d85725e8687c12c01fe7cf9b552/src/map.py#L35-L41

can we do it during one cycle? why do we need to check twice?

**Comment by akorunska** [comment]
Moved checking fullness of each country and checking fullness of whole Europe to one loop in this commit: https://github.com/akorunska/euro-diffusion/commit/3274375cd43b21c18e2976ce27da9300b770c743 
I propose to close this issue.
