### ISSUE TITLE
Checking city fullness

### ISSUE THREAD

**Issue by OleksandrKvitka** [akorunska/euro-diffusion#2]
https://github.com/akorunska/euro-diffusion/blob/8ed415057c9da83bac766db8b6b4811d96c9d81f/src/city.py#L36-L40

Currently fullnes is checked after each citys' balanse updation, even if city is already full. It would be better to check if city is already full (self.full is false) and try to change it afterwards if it's not.

**Comment by akorunska** [comment]
Fixed in https://github.com/akorunska/euro-diffusion/commit/3f3e92c594e608872331bc7ea8e912a0bc2400c8

**Comment by OleksandrKvitka** [comment]
Ok
