### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by OleksandrKvitka** [akorunska/euro-diffusion#4]
https://github.com/akorunska/euro-diffusion/blob/8ed415057c9da83bac766db8b6b4811d96c9d81f/src/country.py#L38

Probably it used to be only_counrty_mode, with letter R.

**Comment by akorunska** [comment]
Fixed in https://github.com/akorunska/euro-diffusion/commit/1f964c23cc2a793ac817aa05aae19f7ba0541354

**Comment by OleksandrKvitka** [comment]
Ok
