### ISSUE TITLE
Only country mode

### ISSUE THREAD

**Issue by OleksandrKvitka** [akorunska/euro-diffusion#5]
https://github.com/akorunska/euro-diffusion/blob/8ed415057c9da83bac766db8b6b4811d96c9d81f/src/country.py#L38-L40

If there is only one country, it is full by definition before the countdown, so day of full should be 0, not 1.

**Comment by akorunska** [comment]
Fixed in https://github.com/akorunska/euro-diffusion/commit/5ac74dd10570f1371f9b8366107b70674b30f6c4

**Comment by OleksandrKvitka** [comment]
Ok
