### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by OleksandrKvitka** [akorunska/euro-diffusion#6]
https://github.com/akorunska/euro-diffusion/blob/8ed415057c9da83bac766db8b6b4811d96c9d81f/src/input.py#L19

No explanation what 0 and 10 are. Better would be to use grid size constant.

**Comment by akorunska** [comment]
Improved in https://github.com/akorunska/euro-diffusion/commit/ca030dc3aaef78322e0fdd694430d1708c4b279e

**Comment by OleksandrKvitka** [comment]
Ok
